services:
  - type: web
    name: gym-management-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://gym_db_qxdo_user:NKp9D98MOz0Rg7VtgLRmCox2G3MpH1p9@dpg-d4mtmvngi27c738j3ks0-a/gym_db_qxdo
    autoDeploy: false

databases:
  - name: GYM-DB
    plan: free