services:
  - type: web
    name: gym-management-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run db:migrate && npm run db:seed && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: gym-db
          property: connectionString
    autoDeploy: false

databases:
  - name: gym-db
    plan: free